CREATE TABLE IF NOT EXISTS otp_challenges (
    id VARCHAR PRIMARY KEY NOT NULL,
    user_id UUID NOT NULL REFERENCES users(id),
    otp_hash VARCHAR NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    otp_expired_at TIMESTAMPTZ NOT NULL,
    deleted_at TIMESTAMPTZ
);
