name: Amarolio CI/CD Pipeline

on:
  push:
    branches:
      - master

# Required permissions to write images to GitHub Packages
permissions:
  contents: read
  packages: write

jobs:
  # ==========================================
  # JOB 1: AMAROLIO CLIENT (Port 5173)
  # ==========================================
  amarolio-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Inject Env
        working-directory: ./client
        run: |
          cat << 'EOF' > .env
          ${{ secrets.PROD_CLIENT_ENV }}
          EOF

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./client
          file: ./client/Dockerfile
          push: true
          tags: ghcr.io/habilamardias/amarolio-client:latest
          

  # ==========================================
  # JOB 2: AMARY CLIENT (Port 4173)
  # ==========================================
  amary-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Inject Env
        working-directory: ./amary-client
        run: |
          cat << 'EOF' > .env
          ${{ secrets.PROD_CLIENT_ENV }}
          EOF

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./amary-client
          file: ./amary-client/Dockerfile
          push: true
          tags: ghcr.io/habilamardias/amary-client:latest
        

  # ==========================================
  # JOB 3: AMARY REDIRECT (Port 8000)
  # ==========================================
  amary-redirect:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Inject Env
        working-directory: ./amary-redirect
        run: |
          cat << 'EOF' > .env
          ${{ secrets.PROD_CLIENT_ENV }}
          EOF

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./amary-redirect
          file: ./amary-redirect/Dockerfile
          push: true
          tags: ghcr.io/habilamardias/amary-redirect:latest

  # ==========================================
  # JOB 4: Amary
  # ==========================================
  amary-amarolio:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./amary
          file: ./amary/Dockerfile
          push: true
          tags: ghcr.io/habilamardias/amary-amarolio:latest

  # ==========================================
  # JOB 5: Auth
  # ==========================================

  auth-amarolio:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./auth
          file: ./auth/Dockerfile
          push: true
          tags: ghcr.io/habilamardias/auth-amarolio:latest
  
  # ==========================================
  # JOB 6: Gateway
  # ==========================================

  gateway-amarolio:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./gateway
          file: ./gateway/Dockerfile
          push: true
          tags: ghcr.io/habilamardias/gateway-amarolio:latest

  # ==========================================
  # JOB 7: Deploy All
  # ==========================================
  deploy-all:
    runs-on: ubuntu-latest
    needs: [amarolio-client, amary-client, amary-redirect, amary-amarolio, auth-amarolio, gateway-amarolio]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Copy docker-compose.yaml
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          password: ${{ secrets.VPS_PASSWORD }}
          source: "docker-compose.yaml"
          target: "/root/apps/amarolio"

      - name: Trigger Remote Docker Compose Up
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          password: ${{ secrets.VPS_PASSWORD }}
          envs: GITHUB_TOKEN,GITHUB_ACTOR
          script: |
            echo "$GITHUB_TOKEN" | docker login ghcr.io -u "$GITHUB_ACTOR" --password-stdin
            cd /root/apps/amarolio

            cat << 'EOF' > .env
            ${{ secrets.PROD_SERVER_ENV }}
            EOF

            docker compose pull
            docker compose up -d
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
        